### PR TITLE
Added a setting to the "Website settings" node to allow us to set the…

### PR DESCRIPTION
**Pull request by filipesousa20**
Added a setting to the "Website settings" node to allow us to set t image quality for all images in the website.

### CODE REVIEW

**Review by ondrejpialek — CHANGES_REQUESTED** [review]
Please remove URI.cs as the same extension method already exists in `/Endzone.Umbraco.Extensions/UriExtensions.cs`

Additionally, are website settings per "site" or per Umbraco install? (e.g. do they live under the home nodes or somewhere under root / a unique folder under root - so there is only one instance)?

**Comment by filipesousa20** [comment]
@ondrejpialek Just moved the method. The setting is in the "Website settings" node as I said, so it's per website and not per installation.

**Comment by ondrejpialek** [comment]
@filipesousa20 Thanks! I checked HHH and it seems we indeed have different setting nodes for each site, so that makes sense.

What bothers me is that we have two methods that are meant to do the same - set a query string parameter. The existing one isn't working with relative URLs, but I would not solve this problem by adding another specialized method that works for that case. While your solution technically works, it creates an API that is hard to use - we will wonder in the future which method to use. Could you refactor the existing methods to make them work with relative URLs, which was the intention in the first place?

I think a simple change would do the trick - first, change the private `SetParameter` method not take in Uri and to return string. Then inside this method you simply split the URL into two parts (split by '?', similarly to what happens in `AbsoluteUriExcludingQuery` - which can go altogether). Then what you pass into the `ParseQueryString` should be anything from the url after the `?` character / or an empty string. And finally, once you get the modified params, you should append those to the first part of the original URL.

This will make it work for relative URLs and we will only have one method that does this.

I do like the change overall, and I did not know you can change the quality on non-crop images as well, that is cool. This is just a minor issue but I think it's worthwile to keep the API clean as we want it to stay around for a long time.

**Comment by filipesousa20** [comment]
@ondrejpialek thanks. You you care to add you suggestion to the code base?

**Comment by ondrejpialek** [comment]
@filipesousa20 I did wonder whether I should do the change myself since I gave you step by step instructions anyway. But then I though that would defeat the purpose of doing the Pull Requests. I hope you are not angry at me for delaying your work, but the change should be quick (that is actually why I was so detailed in my response) and I hope you agree with the comments I made? If it is not critical we can always leave this PR hanging until you have a bit more time?

**Comment by filipesousa20** [comment]
@ondrejpialek this PR is useful to reduce the loading size of some websites. 
I think that adding all that text instead of making the changes is just making us wasting time moving back and forth. 
I appreciate your time to review this PR but if you had just made that change in code, I could review it and we could get this sorted quicker.

**Comment by ondrejpialek** [comment]
@filipesousa20 I agree that it is useful, no doubt about that. I also think that it is great that you added this to the library and that many sites will benefit greatly just by updating the package next time (well, once they set the quality through the backoffice). I don't agree that we are wasting time though - if we are learning we are investing in us, the project and in the company going forward.

That is why I was asking if you think that my concerns were valid, or if you think I am being too strict about that. I think that having a small but well designed library like this is better than having a large library of useful things that is however hard to understand or maintain. I also don't want to change your code when I don't like some aspects of it, but rather discuss that with you, so that we agree on what is important and how this should be done in the future so that there is no need to fix anything.

The last thing I want to do though is to dictate anything, so while it may seem like a lot of useless words I think it's good to have a debate.

**Comment by filipesousa20** [comment]
@ondrejpialek I think it's useful to have a debate yes but it does not prevent you from also adding your proposed changes to the code.
I just don't want to go through all that text, implementing all the changes you suggested when I have lots of other things to do.

**Review by ondrejpialek — APPROVED** [review]

**Pull request merged**
