### PR TITLE
Add recursive support to GetMultipleTypedMedia method.

### PR DESCRIPTION
**Pull request by filipesousa20**
From https://trello.com/c/BakP7oYi/2404-umbraco-extensions-add-recursive-support-to-getmultipletypedmedia-method

### CODE REVIEW

**Comment by barryokane** [comment]
@filipesousa20 code looks OK to me, but one question : I tested something similar a few weeks ago and got an error when I tried it on an Umbraco site.  What version of Umbraco did you test this on?

**Comment by tomvanenckevort-hp** [comment]
@barryokane Was this on a v7.6.x site? Because it could be because of the default PropertyValueConverters that were included from that version onwards (which removes the need to use this method for new sites, as you can directly call `content.GetPropertyValue<IEnumerable<IPublishedContent>>("alias")`).

**Comment by barryokane** [comment]
@tomvanenckevort-ez Ah yes, that is likely what I was seeing.  So this PR should be fine on earlier Umbraco versions, right?

I guess that raises the question as to how we update the whole Extensions package to avoid breaking changes when a site is upgraded to 7.6?

**Comment by tomvanenckevort-hp** [comment]
@barryokane By default the property value converters are turned off (I believe) when upgrading from an older version to v7.6, so it shouldn't affect those sites. But there is a check to see if property value converters have been enabled: `UmbracoConfig.For.UmbracoSettings().Content.EnablePropertyValueConverters`. Not sure if that exists on older Umbraco versions though...

**Comment by filipesousa20** [comment]
By default our sites have property value converters turned off even UmbracoBase. We will need to upgrade the package to support these before enabling them. @tomvanenckevort-ez @barryokane

**Pull request closed without merging**
