### PR TITLE
Fixes a couple of bugs with image quality and tags.

### PR DESCRIPTION
**Pull request by filipesousa20**
I found a couple of bugs. 

- When trying to get the Image quality in a nested content element or the 'website settings' node, it has no knowledge of the home page.
- When the tags property is not using a property converter, it gets returned as a string as opposed to an array of strings.

### CODE REVIEW

**Comment by ondrejpialek** [comment]
Hi Filipe, cool.

What do you think about actually setting the image quality in AppSettings? I guess the users of the CMS will not change this on a regular basis - probably will be set to the same value for all our sites going forward. Would also make it simpler to use on sites that do not have the Website Settings nodes at all.

For the tags fix, that looks fine. How about using the new C#7 feature I showed you the other day in Bansko? 

```
if (item.GetPropertyValue(property) is string)
{
	taglist.AddRange(item.GetPropertyValue<string>(property).Split(','));
}
else
{
	taglist.AddRange(item.GetPropertyValue<string[]>(property) ?? Enumerable.Empty<string>());
}
```

could be turned into

```
var tags = item.GetPropertyValue(property)
if (tags is string s)
{
	taglist.AddRange(s.Split(','));
}
else if (tags is string[] a)
{
	taglist.AddRange(a);
}
```

the advantage is that this is more readable and that you are only accessing the property once (who knows how Umbraco works when you call the generic GetPropertyValue method.

**Comment by filipesousa20** [comment]
@ondrejpialek 

- Good point on c# 7 features. Will just need to add support for c# 7 to the project.
- Yes, they won't need to change the image quality often. My purpose is to give them this possibility without them coming to us but I guess Simon is able to set this up in web.config.

**Comment by ondrejpialek** [comment]
@filipesousa20 I think we will have that in UmbracoBase eventually, so Simon won't have to do that for projects going forward. I was even thinking about setting the default to like 90%, so that all projects would get the benefits just by adding this package (but this would have to be approved by Simon).

Re C#7 so long as you have Visual studio 2017 it will just work, no need to modify the project in any way. I do have the latest update installed though I think (VS 2017 version 15.2 --- funny version numbering)

**Comment by filipesousa20** [comment]
@ondrejpialek so I guess I can keep both on website settings and on web.config. Website settings will take precedence though.

**Comment by ondrejpialek** [comment]
@filipesousa20 I think that would overcomplicate it even further. I suggested appSettings due to simplicity. Pick one or the other, whatever makes more sense to you.

**Comment by filipesousa20** [comment]
@ondrejpialek hmm  If you think we should have it in UmbracoBase why not add it now?

**Edit:** Also we can easily add website settings nodes to older websites.

**Comment by ondrejpialek** [comment]
@filipesousa20 Yes, it can be added now, I think it is a useful feature. Whoever has time can jump on that.

**Comment by filipesousa20** [comment]
@ondrejpialek actually it is working already. I only had to add a textbox field to Umbraco Settings.

**Comment by ondrejpialek** [comment]
Awesome, thanks @filipesousa20.

**Comment by filipesousa20** [comment]
The project was referencing packages from my test solution, that's where the errors came from.
I have to add the compilers package for the build to work with these C# extensions. I'm still using VS 2015 and that might be the reason.

**Comment by ondrejpialek** [comment]
Cool, the build is now passing, so I will approve.

**Review by ondrejpialek — APPROVED** [review]

**Pull request merged**
