### PR TITLE
Fix bug in image quality

### PR DESCRIPTION
**Pull request by filipesousa20**

### CODE REVIEW

**Comment by barryokane** [comment]
@filipesousa20 the code fix looks good to me - however this PR seems to have a duplicate commit from the [PR 9](https://github.com/EndzoneSoftware/Umbraco.Extensions/pull/9) too?  

I don't think that will matter, if you go ahead and merge the PR 9 first.  I think you'll need to cherry pick commits for separate PRs in the future though.

**Comment by ondrejpialek** [comment]
@barryokane @filipesousa20 The issue was that Filipe based this fix off his latest work (the other feature / fix branch). What you should have done instead was to checkout master first and only then create this new branch. Remember - you want the branches to be independent, so you always start of what is on master.

To fix this, you could just rebase this branch onto master. That would get rid of the extra commit in history (no need to cherrypick, that creates a duplicate commit; rebase moves them).

I have however merged the previouc PR and will approve and merge this one too, just so that the fix is there.

One thing for thoughts - I dont understand why we are using the RegEx here, as `int.TryParse()` would do just fine.

**Review by ondrejpialek — APPROVED** [review]

**Comment by barryokane** [comment]
Thanks Ondrej!

Re regex : good point, no idea why that's there.  I'll create an issue so it can be refactored in the future.

**Comment by filipesousa20** [comment]
@ondrejpialek @barryokane 

- I thought I had these two items in separate pull requests. I'll need to double check in the future.
- The regex is there because the image quality has a range from 1 to 100. You don't want someone to enter a number outside that range.

**Pull request merged**
